Birthday-2024-Project/MainScenes/main_level.tscn
Birthday-2024-Project/ScenePrefabs/PuzzleUiManager.tscn
Birthday-2024-Project/Scripts/Game/States/GameEmptyState.gd
Birthday-2024-Project/Scripts/Game/States/GamePlayState.gd
Birthday-2024-Project/Scripts/Game/States/GameState.gd
Birthday-2024-Project/Scripts/Game/States/GameWinState.gd
Birthday-2024-Project/Scripts/GameManager.gd
Birthday-2024-Project/Scripts/GridLogic.gd
Birthday-2024-Project/Scripts/UI/Puzzle/PuzzleMainScreen.gd
Birthday-2024-Project/Scripts/UI/Puzzle/PuzzleUiManager.gd
Birthday-2024-Project/Scripts/UI/Puzzle/States/PuzzleUiPlayState.gd
Birthday-2024-Project/Scripts/UI/Puzzle/States/PuzzleUiState.gd
Birthday-2024-Project/Scripts/UI/Puzzle/States/PuzzleUiWinState.gd

Added game states to `GameManager` to handle play and win states.
https://github.com/Saplings-Projects/Birthday-2024/issues/4
- Signal to `GridLogic` to emit event when a tile is placed
- Getter for free spaces to `GridLogic`
- `GameState` class
- `GameEmptyState` class
- `GamePlayState` class
- `GameWinState` class
- Added initial states to `GameManager`
- Added initial UI to main scene for resetting the puzzle and displaying when the game is won
- `GameManager` now disables interacting with puzzle pieces after winning
None
I think game states could be a good way of splitting up some game logic and make it easier to manage things. Such as making pieces only interactable during play state.

Win condition and game state

---

Birthday-2024-Project/MainScenes/main_menu.tscn
Birthday-2024-Project/ScenePrefabs/MainMenuController.tscn
Birthday-2024-Project/ScenePrefabs/MainMenuUiManager.tscn
Birthday-2024-Project/Scripts/Game/MainMenu/MainMenuController.gd
Birthday-2024-Project/Scripts/Game/MainMenu/States/MainMenuEmptyState.gd
Birthday-2024-Project/Scripts/Game/MainMenu/States/MainMenuStartState.gd
Birthday-2024-Project/Scripts/Game/MainMenu/States/MainMenuState.gd
Birthday-2024-Project/Scripts/UI/MainMenu/MainMenuStartScreen.gd
Birthday-2024-Project/Scripts/UI/MainMenu/MainMenuUiManager.gd
Birthday-2024-Project/Scripts/UI/MainMenu/States/MainMenuUiStartState.gd
Birthday-2024-Project/Scripts/UI/MainMenu/States/MainMenuUiState.gd
Birthday-2024-Project/Scripts/UI/Puzzle/PuzzleUiManager.gd
Birthday-2024-Project/project.godot

Added initial classes and scenes to support a main menu for players to navigate to different scenes.
https://github.com/Saplings-Projects/Birthday-2024/issues/9
- Added initial class `MainMenuController`
- Added initial class `MainMenuState`
- Added initial class `MainMenuEmptyState`
- Added initial class `MainMenuStartState`
- Added initial class `MainMenuStartState`
- Added initial class `MainMenuUiManager`
- Added initial class `MainMenuStartScreen`
- Added initial class `MainMenuUiState`
- Added initial class `MainMenuUiStartState`
- Added scene prefab for a main menu controller
- Added scene prefab for a main menu UI manager
- Added initial main menu scene
- The main menu scene is now the default scene for the project
None
None

Added initial main menu

---

Birthday-2024-Project/Resources/Video/1366x768.tres
Birthday-2024-Project/Resources/Video/1440x900.tres
Birthday-2024-Project/Resources/Video/1920x1080.tres
Birthday-2024-Project/ScenePrefabs/GameMaster.tscn
Birthday-2024-Project/ScenePrefabs/SettingsWindow.tscn
Birthday-2024-Project/Scripts/Game/AudioController.gd
Birthday-2024-Project/Scripts/Game/GameMaster.gd
Birthday-2024-Project/Scripts/Game/SaveSystem.gd
Birthday-2024-Project/Scripts/Game/VideoController.gd
Birthday-2024-Project/Scripts/Model/Prefs/AudioPreferences.gd
Birthday-2024-Project/Scripts/Model/Prefs/Preferences.gd
Birthday-2024-Project/Scripts/Model/Prefs/UserPreferences.gd
Birthday-2024-Project/Scripts/Model/Prefs/VideoPreferences.gd
Birthday-2024-Project/Scripts/Model/ScreenResolution.gd
Birthday-2024-Project/Scripts/UI/Settings/AudioSettingsControl.gd
Birthday-2024-Project/Scripts/UI/Settings/SettingsWindow.gd
Birthday-2024-Project/Scripts/UI/Settings/VideoSettingsControl.gd
Birthday-2024-Project/project.godot

Adds a global game master node that holds global data and has controllers for managing that data. Also adds a save system that is at present able to save and load user data and reworks the settings window around the new system.
https://github.com/Saplings-Projects/Birthday-2024/issues/22
- Script and resources for screen resolution options
- Scripts for user preferences
- Script for a save system for saving and loading data
- Controllers for video and audio settings
- `GameMaster` script and global singleton
- Labels for video settings
- Settings window now relies on controllers in global game master for applying settings
- Screen resolution options are now based on a `ScreenResolution` resource array from game master's video controller
None
In the video settings tab, if a setting is not …

Add game master and controllers for managing user settings

---

Birthday-2024-Project/Scripts/PieceLogic.gd

Removed one of the sounds playing while grabbing a piece
https://github.com/Saplings-Projects/Birthday-2024/issues/30
-removed part of the code from play_grab_audio()
A possible solution to double sound. Should we merge grab and Fauna sounds into one pool?

idea for souble sounds solution

---

Birthday-2024-Project/Scripts/GameManager.gd
Birthday-2024-Project/Scripts/GridLogic.gd
Birthday-2024-Project/Scripts/PieceLogic.gd

Updated the code so that the pieces have better movement when held.
This is closer to what I saw of the real game, and I think it feels better.
Not exactly related to an issue, although it should change #42. I'm not 100% happy with the rotation yet though,  it could be smoother.
- The mouse will always be grabbing the same cell of the piece, which will maintain even when rotating
- When over the grid, the piece will move to its placed position and not move until the mouse moves out of the same grid cell
<br/>
- GameManager.gd - Various changes in piece movement and settling
- GridLogic.gd - Added function that checks if a position is off grid, rather than a piece
- PieceLogic.gd - Changed _input() and related functions to send the clicked cell index to the game manager

Pieces follow the mouse and lock into the grid more smoothly

---

Birthday-2024-Project/Art/OfficialPieceArt/Campaign_normal.png.import
Birthday-2024-Project/Art/OfficialPieceArt/Campaign_pressed.png.import
Birthday-2024-Project/Art/OfficialPieceArt/Level_type_normal.png.import
Birthday-2024-Project/MainScenes/campaign_selection.tscn
Birthday-2024-Project/MainScenes/sapling_level_select_5.tscn
Birthday-2024-Project/ScenePrefabs/CreditsScreen.tscn
Birthday-2024-Project/ScenePrefabs/MainMenuUiManager.tscn

Adjustments after merging the Community assets update and Credits screen PRs.
Made a number of adjustments based on preference that can be reversed depending on opinions and feedback
- some missing import files
- anchoring Campaign Select text label to handle resolution changes
- Sapling Level Select page 5 label updated to "Sapling Levels" like other pages
- Main Menu messages button text changed to "Sapling Messages" similar to "Sapling Levels"
- Preferred adjustments to Credits:
1. Removed outline on texts
2. Standardized name texts to 30
3. Removed extra font size tags that were the same as the theme override
4. Added title text bar similar to other screens
5. Standardized headers and subheaders to 50 size
6. Added spacing between headers
7. Changed Art super header to 60 size
8. …

UI Adjustments after merge

---

Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel1.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel10.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel11.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel12.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel13.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel14.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel15.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel16.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel17.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel2.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel3.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel4.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel5.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel6.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel7.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel8.tres
Birthday-2024-Project/Resources/CampaignLevels/CampaignLevel9.tres
Birthday-2024-Project/Scripts/Game/States/GameWinState.gd
Birthday-2024-Project/Scripts/GameManager.gd
Birthday-2024-Project/Scripts/UI/CampaignSelect/LevelsSelectMenu.gd

The skip button is currently unintuitive as in reality, it doesn't skip levels that someone hasn't beaten yet and just returns to level select. This small PR changes it and the skip button allows skipping levels to locked ones. It will unlock them but won't mark them as complete, the miniature will still feature blank level when it is implemented for all of them.
https://github.com/Saplings-Projects/Birthday-2024/issues/83
- removed the path that leads to the level select screen when skipping to the locked level
- now skip button will lead to the next level unless it's the last one
- skip button will unlock levels but won;t mark them as complete

Skip button update

---

Birthday-2024-Project/export_presets.cfg

Add the export template for Linux platform under X11.
None (got asked by @Casulono )
- Just that commit to add the template
None
the build/Linux directory should be created first (I tried to follow already established convention but since it's outside the git directory i can't control the file structure to make the directory myself)

Add Linux export template

---

Birthday-2024-Project/ScenePrefabs/CreditsScreen.tscn

When the credits window is resized or changes aspect ration (in settings), it clipped the bottom of the credits text. Just added a little padding
https://github.com/Saplings-Projects/Birthday-2024/issues/99
- Added 10 padding to the Vbox between the credits text and copyright text

Fix for Credits text clipping

---

Birthday-2024-Project/Scripts/PieceLogic.gd

Fix to breaking the grid integrity by rapidly spinning pieces in editor mode
https://github.com/Saplings-Projects/Birthday-2024/issues/41
https://github.com/Saplings-Projects/Birthday-2024/issues/53
- Returning pieces use goal rotation instead of current rotation

Editor Rotation Bug Fix

---

Birthday-2024-Project/MainScenes/main_level.tscn
Birthday-2024-Project/Scripts/GameManager.gd
Birthday-2024-Project/Scripts/PieceLogic.gd
Birthday-2024-Project/Scripts/UI/Puzzle/PuzzleMainScreen.gd

If the mouse is hovering a button in the play level, pieces will not be grabbed when clicking even if one or more are behind it.
#116 
- Added a function to PuzzleMainScreen that checks if any of its visible buttons are being hovered by the mouse
- Added a reference to PuzzleMainScreen in GameManager and a function that calls the previous function
- Added logic to PieceLogic that checks if the mouse is over a button and decides it is not clicked

Stop pieces from being grabbed if mouse is hovering a button

---

Birthday-2024-Project/Scripts/UI/MessageGallery.gd

Message Gallery cleans up unused message boxes if a page doesn't use all 4 regions
https://github.com/Saplings-Projects/Birthday-2024/issues/115
- Added a step after page load to check for unused regions and hide corresponding boxes

Message Gallery duplicate message fix

---

Birthday-2024-Project/Scripts/ScreenManagement/SplashScreenController.gd
Birthday-2024-Project/project.godot

Splash screen would transition early if the user clicked early enough before the splash screen appears.
When the resolution gets reseized, it flickers a screenless scene. Changing the screenless background color to black so it's not apparent. Also changed the Godot splash color to black to match the sapling splash
- Added minimum wait of 0.5 sec before splash screen registers click
- Changed screenless BG color to black
- Changed Godot splash screen color to black
I hate that it changes the background color in editor too

Splash screen wait

---

Birthday-2024-Project/Scripts/Game/States/GameEditState.gd
Birthday-2024-Project/Scripts/ScreenManagement/ScreenLogic.gd

Removing the ? at the end of Quit and Restart titles to match other popups
- Removed ? at the end of Quit confirmation popup
- Removed ? at the end of Restart confirmation popup in Editor

Removing the ? at the end of Quit and Restart

---

Birthday-2024-Project/Scripts/UI/Puzzle/PuzzleMainScreen.gd

I've noticed that the snapshot for completion photo takes place immediately after the final piece is in place. This causes the grid to still be gray for this piece. Small delay fixes it.
Without delay:
With delay:
https://github.com/Saplings-Projects/Birthday-2024/issues/141

Introduced small delay before animation start playing

---

Birthday-2024-Project/Resources/TutorialData/TutorialLevel10.tres
Birthday-2024-Project/Resources/TutorialData/TutorialLevel3.tres
Birthday-2024-Project/Resources/TutorialData/TutorialLevel7.tres
Birthday-2024-Project/Resources/TutorialData/TutorialLevel8.tres
Birthday-2024-Project/Resources/TutorialData/TutorialLevel9.tres

Having new Faunas text where not only Faunas were introduced seemed a bit weird
- Changed "New Faunas" to "New pieces" in tutorial prompts with new blockers

Changed "New Faunas" to "New pieces" where blockers were introduced alongside Fauna pieces

---

Birthday-2024-Project/MainScenes/main_level.tscn

Moving level and author name labels to behind the piece grid
https://github.com/Saplings-Projects/Birthday-2024/issues/143
Was easier than I thought since the labels weren't part of the PuzzleUiManager

Moving level and author name labels to not obscure pieces

---

Birthday-2024-Project/Scripts/GridLogic.gd

Instead of widening the area, I fixed the imbalance between positive and negative numbers.
Now left is no longer cut short
https://github.com/Saplings-Projects/Birthday-2024/issues/142
- When calculating safe position, if negative, add one
It's still somewhat conservative because rotating Cape Fauna can lead to some bad situations otherwise

Adjusting Safe Zone

---

Birthday-2024-Project/Scripts/Model/Prefs/VideoPreferences.gd

Users are reporting initializing in fullscreen but it's off-screen so they have no window bar to grab or access to the options button.
Setting default preference to windowed.
Setting default size preference to smaller than 1080 so it's not off the screen

Default as Windowed

---

Birthday-2024-Project/Scripts/ScreenManagement/ScreenManager.gd

Tiny wait before taking screen capture when transitioning scenes, so it doesn't capture the darkened screen
https://github.com/Saplings-Projects/Birthday-2024/issues/153

Flicker Bug Fix

---

Birthday-2024-Project/Scripts/Model/Prefs/AudioPreferences.gd

Audio preferences will have 50% as the starting Fauna noise frequency at first launch
https://github.com/Saplings-Projects/Birthday-2024/issues/155

Default Fauna sound frequency set to 50%

---

Birthday-2024-Project/ScenePrefabs/CreditsScreen.tscn

Following feedback from https://github.com/Saplings-Projects/Birthday-2024/issues/154
https://github.com/Saplings-Projects/Birthday-2024/issues/154
- increased size of server mention to 25
- moved it over the COVER text
- renamed nodes to meaningful names

Placement and size change of server mention

---

Birthday-2024-Project/Scripts/ScreenManagement/ScreenManager.gd
Birthday-2024-Project/Scripts/ScreenManagement/TextPopupController.gd

Buttons would sometime flicker between pressed and hovered state depending on how fast you clicked and when the screen gets captured. Most noticeable on the Campaign Select screen.
Additionally, the wait made it so you can still give inputs in that 0.05 seconds time before the animation puts up a blocker.
Moved the wait to the popup close functionality. Now the transition has instant response again.
https://github.com/Saplings-Projects/Birthday-2024/issues/169
- Removed tiny pre-wait for scene transition animation
- Added tiny wait after the popup animation finishes before it closes
- 
The darken on popups remains when transitioning, but it's not that bad. At least, it didn't seem to flicker

Button flicker fix

---

Birthday-2024-Project/ScenePrefabs/SettingsWindow.tscn
Birthday-2024-Project/Scripts/Game/VideoController.gd
Birthday-2024-Project/Scripts/UI/Settings/VideoSettingsControl.gd

I have a suspicion that some of the weirdness when first launching the game is due to Exclusive Fullscreen.
Since it takes control of the screen and interacts with the gpu.
This changes the fullscreen option to Godot's regular fullscreen mode.
Additionally, fullscreen mode and borderless windowed are effectively the same as far as Godot is concerned, so I removed borderless windowed as an option.
- Removed Borderless Window option from settings popup
- Switched Exclusive Fullscreen mode to regular Fullscreen mode
- Swapped border flags to before (though, I doubt it matters)
- Replaced Borderless Window cases with Fullscreen in case players still have the Borderless Window preference in their save
As far as I can tell, Exclusive Fullscreen is not commonly used anymore. People seem to …

Regular Fullscreen instead of Exclusive Fullscreen
